[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "chance_c"
version = "0.1.0"
license = {file = "LICENSE"}
authors = [
    {name = "Jim Yoon", email = "jim.yoon@pnnl.gov"},
    {name = "Chris R. Vernon", email = "chris.vernon@pnnl.gov"},
]
description = "The CHANCE-C model is a generalized, agent-based modeling framework designed to simulate urban development in flood-prone coastal environments."
readme = "README.md"
requires-python = ">=3.11" # Adjusted based on PyMuPDF and asyncio features
maintainers = [
    {name = "Jim Yoon", email = "jim.yoon@pnnl.gov"},
    {name = "Chris R. Vernon", email = "chris.vernon@pnnl.gov"},
]
classifiers = [
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
]
dependencies = [
    "pynsim>=0.1.5",
    "pandas>=2.3.0",
    "numpy>=2.3.1",
    "geopandas>=1.1.0",
    "scipy>=1.16.0",
    "matplotlib>=3.10.3",
    "contextily>=1.6.2",
    "pyyaml>=6.0.2",
    "click>=8.0.0",
    "numba>=0.60.0",
    "polars>=0.20.0",
    "pyarrow>=10.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov>=2.12.1",
    "trio>=0.30.0",
]
docs = [
    "sphinx~=7.2.6",
    "pydata-sphinx-theme>=0.15.0",
    "myst-parser~=2.0.0",
    "sphinx-autodoc-typehints~=1.25.0",
    "sphinx-copybutton>=0.5.2",
    "sphinx-tabs>=3.4.0",
    "sphinxcontrib-applehelp>=1.0.4",
    "sphinxcontrib-devhelp>=1.0.2",
    "sphinxcontrib-htmlhelp>=2.0.1",
    "sphinxcontrib-jsmath>=1.0.1",
    "sphinxcontrib-qthelp>=1.0.3",
    "sphinxcontrib-serializinghtml>=1.1.5",
    "autodoc>=0.5.0",
    "nbsphinx>=0.9.0",
]
deploy = [
    "twine>=4.0.1",
]

[project.urls]
Repository = "https://github.com/jimyoon/icom_abm"

[project.scripts]
chance-c = "chance_c.cli:cli"

[tool.hatch.build]
packages = ["chance_c"]  # set importable package name to "chance_c"
include = [
    "chance_c",
    "chance_c/data/**/*",
]
